# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: 'github-actions'
    # '/' covers .github/workflows, the glob covers the composite actions
    directories:
      - '/'
      - '/.github/actions/*'
    schedule:
      interval: 'daily'
      # check at 3am UTC
      time: '03:00'
    open-pull-requests-limit: 20
